name: Update Elastic Agent Config

on:
  pull_request:
    branches:
      - main
    paths:
      - 'inputs/*/*/**.yml'

permissions:
  contents: write
  pull-requests: write
  issues: write
  
jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Get changed files using Git
        id: changed-files
        run: |
          # Get the base branch commit
          git fetch origin ${{ github.base_ref }}
          
          echo "=== Debug: All changed files ==="
          git diff --name-only origin/${{ github.base_ref }}...HEAD
          
          echo "=== Debug: Files matching inputs pattern ==="
          git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '^inputs/' || echo "No files match inputs/ pattern"
          
          echo "=== Debug: YAML files in inputs ==="
          git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '^inputs/.*\.yml$' || echo "No YAML files in inputs"
          
          echo "=== Debug: Final filtered files ==="
          # Find changed files matching our pattern - more flexible regex
          changed_files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '^inputs/.*\.yml$' | grep -v 'elastic-agent\.yml$' || true)
          echo "Filtered files: '$changed_files'"
          
          if [ -n "$changed_files" ]; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
            echo "all_changed_files<<EOF" >> $GITHUB_OUTPUT
            echo "$changed_files" | tr '\n' ' ' >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
            echo "all_changed_files=" >> $GITHUB_OUTPUT
          fi

      - name: Debug changed files
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Files changed: ${{ steps.changed-files.outputs.any_changed }}"

      - name: Run update script
        id: update_script
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          output=$(python .github/scripts/update_elastic_agent.py ${{ steps.changed-files.outputs.all_changed_files }} 2>&1)
          echo "$output"
          echo "script_output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Skip update script
        if: steps.changed-files.outputs.any_changed != 'true'
        run: |
          echo "No relevant files changed, skipping update script"

      - name: Commit files
        if: steps.update_script.outcome == 'success'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update elastic-agent.yml from changed inputs" || echo "No changes to commit"
          git push

      - name: Post success PR comment
        if: steps.update_script.outcome == 'success'
        uses: actions/github-script@v6
        with:
          script: |
            const output = `
            #### ✅ Elastic Agent Config Update - Success
            
            The elastic-agent.yml files have been successfully updated with the new input configurations.
            
            **Details:**
            \`\`\`
            ${{ steps.update_script.outputs.script_output }}
            \`\`\`
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: output
            });

      - name: Post failure PR comment
        if: steps.update_script.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          script: |
            const output = `
            #### ❌ Elastic Agent Config Update - Failed
            
            There was an error updating the elastic-agent.yml files.
            
            **Error Details:**
            \`\`\`
            ${{ steps.update_script.outputs.script_output }}
            \`\`\`
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: output
            });